### ISSUE TITLE
Hiera backend

### ISSUE THREAD

**Issue by happymcplaksin** [happymcplaksin/noodle#13]

**Comment by happymcplaksin** [comment]
Close via these:

* https://github.com/happymcplaksin/happymcplaksin-noodle/blob/master/lib/puppet/functions/noodle_lookup_key.rb
* https://github.com/happymcplaksin/happymcplaksin-noodle/blob/master/hiera.yaml#L4-L7

**Comment by happymcplaksin** [comment]
As of [this commit](https://github.com/happymcplaksin/happymcplaksin-noodle/commit/cbeb693e37b982113148d16b7915b842ac2a42ef) to the Noodle Puppet module, it works!

```
root@desmond:~# /usr/local/noodle/bin/noodle desmond
---
classes:
- baseclass
parameters:
  ilk: host
  project: hr
  prodlevel: prod
  site: mars
  status: enabled
  ntp_servers: jojo

root@desmond:~# puppet lookup --render-as s site
mars

root@desmond:~# puppet lookup --render-as s ntp_servers
jojo

root@desmond:~# puppet lookup --render-as s prodlevel
prod

root@desmond:~# /usr/local/noodle/bin/noodlin param role=web,db desmond

root@desmond:~# /usr/local/noodle/bin/noodle desmond
---
classes:
- baseclass
parameters:
  ilk: host
  project: hr
  prodlevel: prod
  site: mars
  status: enabled
  ntp_servers: jojo
  role:
  - web
  - db
```
Since `Noodle.paramvalue` only deals in strings (so far), this fails to DTRT with arrays and such:
```
root@desmond:~# puppet lookup --render-as s role
db,web

root@desmond:~# puppet lookup  role
--- db,web
...
```

But handling non-strings will come soon!

**Comment by happymcplaksin** [comment]
PS: With this hiera.yaml:

```
root@desmond:~# cat /etc/puppetlabs/puppet/hiera.yaml                                                                                        
---                                                                                                                                          
version: 5                                                                                                                                   
hierarchy:                                                                                                                                   
  - name: "Noodle"                                                                                                                           
    lookup_key: noodle_lookup_key                                                                                                            
    options:                                                                                                                                 
      hostname: "%{facts.hostname}"                                                                                                          
  - name: "Per-node data"                   # Human-readable name.                                                                           
    path: "nodes/%{facts.hostname}.yaml"  # File path, relative to datadir.                                                                  
  - name: Common                                                                                                                             
    path: common.yaml                                                                                                                        
defaults:                                                                                                                                    
  data_hash: yaml_data                                                                                                                       
  datadir: data                                                                                                                              
```
